version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatbot-backend-app
    container_name: chatbot-backend-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: ankane/pgvector:latest
    container_name: chatbot-backend-db
    restart: unless-stopped
    networks:
      - laravel-network
    environment:
      POSTGRES_DB: chatbot
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:

networks:
  laravel-network:
    driver: bridge
